-- Migration 0013: user_profile soft-delete column (account closure, 90-day recovery window).
--
-- !!! APPLIED TO PRODUCTION 2026-06-12 (additive nullable column; no backfill needed) !!!
-- Adds `deleted_at timestamptz null` to public.user_profile so a Coordinator can CLOSE
-- their account (POST /api/v3/me/delete) without the data being hard-deleted. Per the
-- retention policy the data is RETAINED for 90 DAYS, during which the Coordinator can
-- REACTIVATE by simply signing back in (POST /api/v3/me/reactivate clears deleted_at). At
-- 90 days the data is permanently deleted by a MANUAL / operational purge (there is no
-- automated purge job; the purge query is documented in supabase/README.md). The
-- hard-delete-due moment is COMPUTED in the api as deleted_at + 90 days (GET
-- /api/v3/me/account-status); it is deliberately NOT a stored column. A null deleted_at means
-- the account is active; a non-null deleted_at means it is closed (soft-deleted) and the
-- api treats the user as gone (the current-user path rejects a soft-deleted account with
-- 410, so a closed account can neither read nor write until it reactivates).
--
-- ADDITIVE and IDEMPOTENT: `add column if not exists` only appends a nullable column;
-- it does not alter or drop anything and changes no existing row (every current row gets
-- deleted_at = null, i.e. active). No RLS change is needed: the existing
-- user_profile_select_own / user_profile_update_own policies (migration 0001) already scope
-- the column to the owner (auth.uid() = id), so the caller reads, sets, and clears their OWN
-- deleted_at under RLS, never anyone else's.
--
-- APPLIED TO PRODUCTION 2026-06-12: this migration has been applied to the production
-- database (the same orchestrated go-live as 0009/0010/0011). The /me/delete write, the
-- reactivation, and the soft-delete access block now have the column to act on. Because the
-- column was absent until this was applied, _read_deleted_at (app/services/account.py) fails
-- open on a read error so the soft-delete read can never 500 the authenticated api.

-- =====================================================================
-- user_profile.deleted_at
-- Null = active account. Non-null = closed (soft-deleted), recoverable for 90 days, then
-- permanently deleted by a manual operational purge.
-- =====================================================================
alter table public.user_profile
    add column if not exists deleted_at timestamptz;
