-- Migration 0013: user_profile soft-delete column (account closure, 90-day recovery window).
--
-- Adds `deleted_at timestamptz null` to public.user_profile so a Coordinator can CLOSE
-- their account (POST /api/v3/me/delete) without the data being hard-deleted. Per the
-- retention policy the data is RETAINED for 90 DAYS, during which the Coordinator can
-- REACTIVATE by simply signing back in (POST /api/v3/me/reactivate clears deleted_at). At
-- 90 days the data is permanently deleted by a MANUAL / operational purge (there is no
-- automated purge job; the purge query is documented in supabase/README.md). The
-- hard-delete-due moment is COMPUTED in the api as deleted_at + 90 days (GET
-- /api/v3/me/account-status); it is deliberately NOT a stored column. A null deleted_at means
-- the account is active; a non-null deleted_at means it is closed (soft-deleted) and the
-- api treats the user as gone (the current-user path rejects a soft-deleted account with
-- 410, so a closed account can neither read nor write until it reactivates).
--
-- ADDITIVE and IDEMPOTENT: `add column if not exists` only appends a nullable column;
-- it does not alter or drop anything and changes no existing row (every current row gets
-- deleted_at = null, i.e. active). No RLS change is needed: the existing
-- user_profile_select_own / user_profile_update_own policies (migration 0001) already scope
-- the column to the owner (auth.uid() = id), so the caller reads, sets, and clears their OWN
-- deleted_at under RLS, never anyone else's.
--
-- PENDING OWNER APPLY: this migration is written but NOT applied to production by this
-- change. The orchestrator/owner applies it (the same posture as migration 0012's deferred
-- follow-ups). Until it is applied, the /me/delete write, the reactivation, and the
-- soft-delete access block have no column to act on.

-- =====================================================================
-- user_profile.deleted_at
-- Null = active account. Non-null = closed (soft-deleted), recoverable for 90 days, then
-- permanently deleted by a manual operational purge.
-- =====================================================================
alter table public.user_profile
    add column if not exists deleted_at timestamptz;
